return {
  outboundFlight: {
    departureAirport: {
      name: "John F. Kennedy International Airport",
      id: "JFK",
      city: "New York",
      country: "United States",
    },
    arrivalAirport: {
      name: "Los Angeles International Airport",
      id: "LAX",
      city: "Los Angeles",
      country: "United States",
    },
    airline: "Mock Airlines",
    flightNumber: "MA123",
    departureTime: "10:00 AM",
    arrivalTime: "1:00 PM",
    duration: "3h 00m",
    price: 299.99,
  },
  returnFlight: {
    departureAirport: {
      name: "Los Angeles International Airport",
      id: "LAX",
      city: "Los Angeles",
      country: "United States",
    },
    arrivalAirport: {
      name: "John F. Kennedy International Airport",
      id: "JFK",
      city: "New York",
      country: "United States",
    },
    airline: "Mock Airlines",
    flightNumber: "MA456",
    departureTime: "3:00 PM",
    arrivalTime: "6:00 PM",
    duration: "3h 00m",
    price: 319.99,
  },
  neighborhoods: [
    {
      name: "Downtown",
      coffeeShops: [
        {
          name: "Urban Brew",
          address: "123 Main St",
          neighborhood: "Downtown",
          review: { score: 4.5, count: 128 },
          description: "Cozy downtown cafe with artisanal coffee",
          googleReviewsUrl: "https://maps.google.com/example",
          photosUrl: "https://example.com/photos",
          websiteUrl: "https://example.com",
        },
        {
          name: "Coffee Haven",
          address: "456 Market St",
          neighborhood: "Downtown",
          review: { score: 4.7, count: 256 },
          description: "Modern cafe with specialty brews and pastries",
          googleReviewsUrl: "https://maps.google.com/example",
          photosUrl: "https://example.com/photos",
          websiteUrl: "https://example.com",
        },
      ],
    },
    {
      name: "Arts District",
      coffeeShops: [
        {
          name: "Gallery Coffee",
          address: "789 Arts Ave",
          neighborhood: "Arts District",
          review: { score: 4.8, count: 189 },
          description: "Artistic cafe featuring local artwork and premium coffee",
          googleReviewsUrl: "https://maps.google.com/example",
          photosUrl: "https://example.com/photos",
          websiteUrl: "https://example.com",
        },
        {
          name: "Creative Cup",
          address: "321 Studio St",
          neighborhood: "Arts District",
          review: { score: 4.6, count: 167 },
          description: "Inspiring coffee shop with creative atmosphere",
          googleReviewsUrl: "https://maps.google.com/example",
          photosUrl: "https://example.com/photos",
          websiteUrl: "https://example.com",
        },
      ],
    },
  ],
  activities: [
    {
      name: "City Museum Tour",
      address: "456 History Ave",
      review: { score: 4.8, count: 350 },
      description: "Fascinating museum showcasing local history",
      websiteUrl: "https://example.com",
      price: 25,
      duration: "2-3 hours",
    },
    {
      name: "Botanical Gardens",
      address: "789 Garden Path",
      review: { score: 4.7, count: 420 },
      description: "Beautiful gardens with rare plant species",
      websiteUrl: "https://example.com",
      price: 15,
      duration: "1-2 hours",
    },
    {
      name: "Local Food Tour",
      address: "101 Foodie Lane",
      review: { score: 4.9, count: 280 },
      description: "Guided tour of local cuisine highlights",
      websiteUrl: "https://example.com",
      price: 65,
      duration: "3 hours",
    },
  ],
  dailyItinerary: [
    {
      date: departureDate.toISOString().split("T")[0] ?? "",
      activities: [
        {
          name: "Arrival & Check-in",
          address: "LAX Airport",
          review: { score: 4.5, count: 1000 },
          description: "Arrive at LAX and check in to your hotel",
          websiteUrl: "https://example.com",
          scheduledDate: departureDate.toISOString().split("T")[0] ?? "",
          startTime: "13:00",
          endTime: "14:30",
        },
      ],
      coffeeShop: {
        name: "Urban Brew",
        address: "123 Main St",
        neighborhood: "Downtown",
        review: { score: 4.5, count: 128 },
        description: "Cozy downtown cafe with artisanal coffee",
        googleReviewsUrl: "https://maps.google.com/example",
        photosUrl: "https://example.com/photos",
        websiteUrl: "https://example.com",
      },
    },
    {
      date: middleDateStr,
      activities: [
        {
          name: "City Museum Tour",
          address: "456 History Ave",
          review: { score: 4.8, count: 350 },
          description: "Fascinating museum showcasing local history",
          websiteUrl: "https://example.com",
          price: 25,
          duration: "2-3 hours",
          scheduledDate: middleDateStr,
          startTime: "10:00",
          endTime: "13:00",
        },
        {
          name: "Botanical Gardens",
          address: "789 Garden Path",
          review: { score: 4.7, count: 420 },
          description: "Beautiful gardens with rare plant species",
          websiteUrl: "https://example.com",
          price: 15,
          duration: "1-2 hours",
          scheduledDate: middleDateStr,
          startTime: "14:00",
          endTime: "16:00",
        },
      ],
      coffeeShop: {
        name: "Gallery Coffee",
        address: "789 Arts Ave",
        neighborhood: "Arts District",
        review: { score: 4.8, count: 189 },
        description: "Artistic cafe featuring local artwork and premium coffee",
        googleReviewsUrl: "https://maps.google.com/example",
        photosUrl: "https://example.com/photos",
        websiteUrl: "https://example.com",
      },
    },
    {
      date: returnDate.toISOString().split("T")[0] ?? "",
      activities: [
        {
          name: "Local Food Tour",
          address: "101 Foodie Lane",
          review: { score: 4.9, count: 280 },
          description: "Guided tour of local cuisine highlights",
          websiteUrl: "https://example.com",
          price: 65,
          duration: "3 hours",
          scheduledDate: returnDate.toISOString().split("T")[0] ?? "",
          startTime: "09:00",
          endTime: "12:00",
        },
        {
          name: "Departure",
          address: "LAX Airport",
          review: { score: 4.5, count: 1000 },
          description: "Head to LAX for your return flight",
          websiteUrl: "https://example.com",
          scheduledDate: returnDate.toISOString().split("T")[0] ?? "",
          startTime: "13:00",
          endTime: "15:00",
        },
      ],
    },
  ],
  loading: false,
  error: null,
}
