name: On Pull Request (any branch)

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  pull-requests: read
  checks: write

jobs:
  lint:
    uses: ./.github/workflows/job-lint.yaml
    secrets: inherit

  # Build and Test job
  build-and-test:
    needs: lint
    uses: ./.github/workflows/job-nest-build-and-test.yaml
    secrets: inherit
